name: Deploy Deployment Notifier

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Application name (e.g., netwin)"
        required: true
        type: string
      env:
        description: "Environment (e.g., Production)"
        required: true
        type: string
      date:
        description: "Deployment Date (YYYY-MM-DD, e.g., 2025-08-27)"
        required: true
        type: string
      time:
        description: "Deployment Time (HH:MM, e.g., 17:00)"
        required: true
        type: string
      downtime:
        description: "Expected Downtime (e.g., 30 minutes)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Prepare public folder
      - name: Prepare public folder
        run: |
          mkdir public
          cp -r deployment-notifier/* public/

      # 3️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # 4️⃣ Print clickable URL with prefilled inputs
      - name: Show Deployment Notifier URL
        run: |
          APP=${{ github.event.inputs.app }}
          ENV=${{ github.event.inputs.env }}
          DATE=${{ github.event.inputs.date }}
          TIME=${{ github.event.inputs.time }}
          DOWNTIME=${{ github.event.inputs.downtime }}

          # URL-encode spaces for downtime
          DOWNTIME_ENCODED=$(echo $DOWNTIME | sed 's/ /%20/g')

          URL="https://<your-username>.github.io/<your-repo>/?app=${APP}&env=${ENV}&date=${DATE}&time=${TIME}&downtime=${DOWNTIME_ENCODED}"
          echo "Deployment Notifier is ready! Open this URL in your browser:"
          echo "$URL"
