name: Deploy Deployment Notifier

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Affected System/Application"
        required: true
        type: choice
        options:
          - Alarm Manager
          - Altaia
          - Altice Agora
          - Analytics
          - FF1
          - FFWK
          - IAM
          - NOSSIS Common
          - NetQ
          - Netwin
          - Nokia AMS
          - SIGO WO
          - SIGO TTK
          - SIGO WOv15
      env:
        description: "Environment"
        required: true
        type: choice
        options:
          - Production
          - Test
          - Pre-Production
      date:
        description: "Deployment Date (YYYY-MM-DD)"
        required: true
        type: string
      time:
        description: "Deployment Time (HH:MM, e.g., 17:00)"
        required: true
        type: string
      downtime:
        description: "Expected Downtime (e.g., 30 minutes)"
        required: true
        type: string
      release:
        description: "Vendor Release Notes / Version"
        required: false
        type: string
        default: "N/A"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          mkdir public
          cp -r deployment-notifier/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Show Deployment Notifier URL
        shell: bash
        run: |
          APP="${{ github.event.inputs.app }}"
          ENV="${{ github.event.inputs.env }}"
          DATE="${{ github.event.inputs.date }}"
          TIME="${{ github.event.inputs.time }}"
          DOWNTIME="${{ github.event.inputs.downtime }}"
          RELEASE="${{ github.event.inputs.release }}"

          # URL encode using jq
          APP_ENC=$(echo "$APP" | jq -s -R -r @uri)
          ENV_ENC=$(echo "$ENV" | jq -s -R -r @uri)
          DATE_ENC=$(echo "$DATE" | jq -s -R -r @uri)
          TIME_ENC=$(echo "$TIME" | jq -s -R -r @uri)
          DOWNTIME_ENC=$(echo "$DOWNTIME" | jq -s -R -r @uri)
          RELEASE_ENC=$(echo "$RELEASE" | jq -s -R -r @uri)

          USERNAME=${GITHUB_REPOSITORY_OWNER}
          REPO=$(basename $GITHUB_REPOSITORY)

          URL="https://${USERNAME}.github.io/${REPO}/?app=${APP_ENC}&env=${ENV_ENC}&date=${DATE_ENC}&time=${TIME_ENC}&downtime=${DOWNTIME_ENC}&release=${RELEASE_ENC}"

          echo "Deployment Notifier URL:"
          echo "$URL"
