name: Deployment Notifier

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Affected System/Application"
        required: true
        type: choice
        options:
          - Alarm Manager
          - Altaia
          - Altice Agora
          - Analytics
          - FF1
          - FFWK
          - IAM
          - NOSSIS Common
          - NetQ
          - Netwin
          - Nokia AMS
          - SIGO WO
          - SIGO TTK
          - SIGO WOv15
      env:
        description: "Environment"
        required: true
        type: choice
        options:
          - Production
          - Test
          - Pre-Production
      date:
        description: "Deployment Date (YYYY-MM-DD)"
        required: true
        type: string
      time:
        description: "Deployment Time (HH:MM, e.g., 17:00)"
        required: true
        type: string
      downtime:
        description: "Expected Downtime (e.g., 30 minutes)"
        required: true
        type: string
      release:
        description: "Vendor Release Notes / Version"
        required: false
        type: string
        default: "N/A"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set deployment variables
        id: vars
        run: |
          echo "APP=${{ github.event.inputs.app }}" >> $GITHUB_ENV
          echo "ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV
          echo "DATE=${{ github.event.inputs.date }}" >> $GITHUB_ENV
          echo "TIME=${{ github.event.inputs.time }}" >> $GITHUB_ENV
          echo "DOWNTIME=${{ github.event.inputs.downtime }}" >> $GITHUB_ENV
          echo "RELEASE=${{ github.event.inputs.release }}" >> $GITHUB_ENV

      - name: Generate deployment summary
        id: summary
        run: |
          SUMMARY_FILE=deploy_summary.txt
          echo "deploy summary" > $SUMMARY_FILE
          echo "Deployment Notifier" >> $SUMMARY_FILE
          echo "App: $APP" >> $SUMMARY_FILE
          echo "Environment: $ENV" >> $SUMMARY_FILE
          echo "Date: $DATE" >> $SUMMARY_FILE
          echo "Time: $TIME" >> $SUMMARY_FILE
          echo "Downtime: $DOWNTIME" >> $SUMMARY_FILE
          echo "Release: $RELEASE" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "Open Pre-Filled Form" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "Note: Excel files must exist at deployment-notifier/users/<App>.xlsx (e.g., users/$APP.xlsx)." >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "Job summary generated at run-time" >> $SUMMARY_FILE
          echo "SUMMARY_FILE=$SUMMARY_FILE" >> $GITHUB_OUTPUT

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-summary
          path: ${{ steps.summary.outputs.SUMMARY_FILE }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: ./  # or your actual build folder if using static site generator
