name: Deployment Notifier

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Affected System/Application"
        required: true
        type: choice
        options:
          - Alarm Manager
          - Altaia
          - Altice Agora
          - Analytics
          - FF1
          - FFWK
          - IAM
          - NOSSIS Common
          - NetQ
          - Netwin
          - Nokia AMS
          - SIGO WO
          - SIGO TTK
          - SIGO WOv15
      env:
        description: "Environment"
        required: true
        type: choice
        options:
          - Production
          - Test
          - Pre-Production
      date:
        description: "Deployment Date (YYYY-MM-DD)"
        required: true
        type: string
      time:
        description: "Deployment Time (HH:MM, e.g., 17:00)"
        required: true
        type: string
      downtime:
        description: "Expected Downtime (e.g., 30 minutes)"
        required: true
        type: string
      release:
        description: "Vendor Release Notes / Version"
        required: false
        type: string
        default: "N/A"

jobs:
  deploy-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Deployment Summary
        run: |
          echo "deploy summary" > summary.txt
          echo "Deployment Notifier" >> summary.txt
          echo "App: ${{ github.event.inputs.app }}" >> summary.txt
          echo "Environment: ${{ github.event.inputs.env }}" >> summary.txt
          echo "Date: ${{ github.event.inputs.date }}" >> summary.txt
          echo "Time: ${{ github.event.inputs.time }}" >> summary.txt
          echo "Downtime: ${{ github.event.inputs.downtime }}" >> summary.txt
          echo "Release: ${{ github.event.inputs.release }}" >> summary.txt
          echo "" >> summary.txt
          echo "Open Pre-Filled Form" >> summary.txt
          echo "" >> summary.txt
          echo "Note: Excel files must exist at deployment-notifier/users/<App>.xlsx (e.g., users/${{ github.event.inputs.app }}.xlsx)." >> summary.txt
          echo "" >> summary.txt
          echo "Job summary generated at run-time" >> summary.txt

      - name: Upload Deployment Summary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-summary
          path: summary.txt

      - name: Output Pre-Filled Form Link
        run: |
          FORM_URL="https://<YOUR-GITHUB-PAGES-URL>/index.html?app=${{ github.event.inputs.app }}&env=${{ github.event.inputs.env }}&date=${{ github.event.inputs.date }}&time=${{ github.event.inputs.time }}&downtime=${{ github.event.inputs.downtime }}&release=${{ github.event.inputs.release }}"
          echo "Pre-Filled Form Link: $FORM_URL"
          echo "Pre-Filled Form Link: $FORM_URL" >> $GITHUB_STEP_SUMMARY
