name: Deploy Deployment Notifier

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Application name (e.g., Netwin)"
        required: true
        type: string
      env:
        description: "Environment (e.g., Production)"
        required: true
        type: string
      date:
        description: "Deployment Date (YYYY-MM-DD)"
        required: true
        type: string
      time:
        description: "Deployment Time (HH:MM, e.g., 17:00)"
        required: true
        type: string
      downtime:
        description: "Expected Downtime (e.g., 30 minutes)"
        required: true
        type: string
      release:
        description: "Vendor Release Notes / Version"
        required: false
        type: string
        default: "N/A"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          mkdir public
          cp -r deployment-notifier/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Show Deployment Notifier URL
        shell: bash
        run: |
          APP="${{ github.event.inputs.app }}"
          ENV="${{ github.event.inputs.env }}"
          DATE="${{ github.event.inputs.date }}"
          TIME="${{ github.event.inputs.time }}"
          DOWNTIME="${{ github.event.inputs.downtime }}"
          RELEASE="${{ github.event.inputs.release }}"

          # URL encode
          APP_ENC=$(echo "$APP" | sed 's/ /%20/g')
          ENV_ENC=$(echo "$ENV" | sed 's/ /%20/g')
          DATE_ENC="$DATE"
          TIME_ENC="$TIME"
          DOWNTIME_ENC=$(echo "$DOWNTIME" | sed 's/ /%20/g')
          RELEASE_ENC=$(echo "$RELEASE" | sed 's/ /%20/g')

          USERNAME=${GITHUB_REPOSITORY_OWNER}
          REPO=$(basename $GITHUB_REPOSITORY)

          URL="https://${USERNAME}.github.io/${REPO}/?app=${APP_ENC}&env=${ENV_ENC}&date=${DATE_ENC}&time=${TIME_ENC}&downtime=${DOWNTIME_ENC}&release=${RELEASE_ENC}"

          echo "✅ Deployment Notifier URL:"
          echo "$URL"
