name: Deploy Deployment Notifier

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Application name (e.g., Netwin)"
        required: true
        type: string
        default: "Netwin"
      env:
        description: "Environment (Production, Test, Pre-Production)"
        required: true
        type: choice
        options:
          - Production
          - Test
          - Pre-Production
        default: Production
      date:
        description: "Deployment Date (YYYY-MM-DD, leave 'TODAY' for current date)"
        required: true
        type: string
        default: "TODAY"
      time:
        description: "Deployment Time (HH:MM, 24-hour format)"
        required: true
        type: string
        default: "17:00"
      downtime:
        description: "Expected Downtime (e.g., 30 minutes)"
        required: true
        type: string
        default: "30 minutes"
      release:
        description: "Vendor Release Notes / Version"
        required: false
        type: string
        default: "N/A"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Prepare public folder
      - name: Prepare public folder
        run: |
          mkdir -p public
          cp -r deployment-notifier/* public/

      # 3️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # 4️⃣ Show clickable URL with prefilled inputs
      - name: Show Deployment Notifier URL
        shell: bash
        run: |
          APP="${{ github.event.inputs.app }}"
          ENV="${{ github.event.inputs.env }}"
          DATE="${{ github.event.inputs.date }}"
          TIME="${{ github.event.inputs.time }}"
          DOWNTIME="${{ github.event.inputs.downtime }}"
          RELEASE="${{ github.event.inputs.release }}"

          # Replace placeholder with current date if needed
          if [ "$DATE" = "TODAY" ]; then
            DATE=$(date +%Y-%m-%d)
          fi

          # URL-encode spaces
          DOWNTIME_ENCODED=$(echo "$DOWNTIME" | sed 's/ /%20/g')
          RELEASE_ENCODED=$(echo "$RELEASE" | sed 's/ /%20/g')

          # Get username and repo dynamically
          USERNAME=${GITHUB_REPOSITORY_OWNER}
          REPO=$(basename $GITHUB_REPOSITORY)

          URL="https://${USERNAME}.github.io/${REPO}/?app=${APP}&env=${ENV}&date=${DATE}&time=${TIME}&downtime=${DOWNTIME_ENCODED}&release=${RELEASE_ENCODED}"

          echo "Deployment Notifier is ready! Open this URL in your browser:"
          echo "$URL"
